backend:
  name: git-gateway
  publish_mode: editorial_workflow
  
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/upload

collections:
  - name: "play" # Used in routes, e.g., /admin/collections/blog
    label: "Play Section" # Used in the UI
    folder: "content/play" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: "false"}
      - {label: "Scripts", name: "scripts", widget: "string", required: "false"}
      - {label: "Tags", name: "tags", widget: "string", required: "false"}
      - {label: "Draft", name: "draft", widget: "boolean", default: "false"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "tech" # Used in routes, e.g., /admin/collections/blog
    label: "Tech Section" # Used in the UI
    folder: "content/tech" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "tech"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: "false"}
      - {label: "Scripts", name: "scripts", widget: "string", required: "false"}
      - {label: "Tags", name: "tags", widget: "string", required: "false"}
      - {label: "Draft", name: "draft", widget: "boolean", default: "false"}
      - {label: "Body", name: "body", widget: "markdown"}
